# Generated by Django 5.2.12 on 2026-04-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homecare", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medication",
            name="frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("daily", "Daily"),
                    ("twice_daily", "Twice Daily"),
                    ("three_times_daily", "Three Times Daily"),
                    ("four_times_daily", "Three Times Daily"),
                    ("each_hour", "Each Hour"),
                    ("weekly", "Weekly"),
                    ("as_needed", "As needed"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
