# Generated by Django 5.2.12 on 2026-04-18 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homecare", "0006_patientcaretakerassignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientDailyClinicalReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_date",
                    models.DateField(
                        db_index=True,
                        help_text="Calendar day in Asia/Kathmandu (see settings.TIME_ZONE).",
                    ),
                ),
                (
                    "medication_summary",
                    models.JSONField(
                        default=dict,
                        help_text="Structured medication adherence for the day (logs + optional schedule context).",
                    ),
                ),
                ("medication_summary_text", models.TextField(blank=True, default="")),
                (
                    "vitals_summary",
                    models.JSONField(
                        default=dict,
                        help_text="Structured vitals for the day (readings and/or aggregates).",
                    ),
                ),
                ("vitals_summary_text", models.TextField(blank=True, default="")),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_clinical_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-report_date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["patient", "-report_date"],
                        name="homecare_pa_patient_fa58e7_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("patient", "report_date"),
                        name="uniq_patient_daily_clinical_report",
                    )
                ],
            },
        ),
    ]
