# Generated by Django 5.2.12 on 2026-04-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('staff', 'Staff'), ('home_care_staff', 'Home Care Staff'), ('pharmacy_staff', 'Pharmacy Staff'), ('home_care_patient', 'Home Care Patient'), ('patient', 'Patient')], default='admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('customer', 'Customer'), ('staff', 'Staff'), ('home_care_staff', 'Home Care Staff'), ('pharmacy_staff', 'Pharmacy Staff'), ('home_care_patient', 'Home Care Patient'), ('patient', 'Patient')], default='patient', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='publicuserprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('staff', 'Staff'), ('home_care_staff', 'Home Care Staff'), ('pharmacy_staff', 'Pharmacy Staff'), ('home_care_patient', 'Home Care Patient'), ('patient', 'Patient')], default='customer', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('staff', 'Staff'), ('home_care_staff', 'Home Care Staff'), ('pharmacy_staff', 'Pharmacy Staff'), ('home_care_patient', 'Home Care Patient'), ('patient', 'Patient')], default='pharmacy_staff', max_length=100),
        ),
    ]
