# Generated by Django 5.2.12 on 2026-04-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Location name ", max_length=200)),
                ("street", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                (
                    "google_location_links",
                    models.TextField(help_text="Store Google Maps share links"),
                ),
                (
                    "google_maps_embed",
                    models.TextField(
                        help_text="Paste the Google Maps iframe embed code here"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
