# Generated by Django 5.2.12 on 2026-04-02 15:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

from common.image_validators import validate_image_file_size


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=100)),
                ("contact_number", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("address", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
            },
        ),
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="medicine_images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            ),
                            validate_image_file_size,
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "generic_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("brand_name", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("strength", models.CharField(help_text="e.g. 500mg", max_length=50)),
                ("requires_prescription", models.BooleanField(default=False)),
                (
                    "reorder_level",
                    models.PositiveIntegerField(
                        default=10, help_text="Alert when stock falls below this level"
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("manufacturing_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("quantity_received", models.PositiveIntegerField(default=0)),
                ("quantity_remaining", models.PositiveIntegerField(default=0)),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "selling_price_after_discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medicines",
                        to="pharmacy.category",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medicines",
                        to="pharmacy.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
