# Generated by Django 5.2.12 on 2026-04-03 18:53

import common.image_validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="medicine_images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    ),
                    common.image_validators.validate_image_file_size,
                    common.image_validators.validate_image_file_integrity,
                ],
            ),
        ),
    ]
